# Generated by Django 5.2.15 on 2026-06-23 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportIFTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(blank=True, default="", max_length=50)),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                ("vehicles", models.TextField(blank=True, default="")),
                ("report", models.CharField(blank=True, default="", max_length=100)),
                ("processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "report_ifta",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RtlDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rtl_id", models.CharField(max_length=100, unique=True)),
                (
                    "company_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("email", models.CharField(blank=True, default="", max_length=255)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("phone_num", models.CharField(blank=True, default="", max_length=50)),
                (
                    "license_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "license_state",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "rtl_created_at",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "rtl_updated_at",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rtl_driver",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="RtlIfta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rtl_id", models.CharField(max_length=100, unique=True)),
                (
                    "company_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("type_id", models.CharField(blank=True, default="", max_length=50)),
                ("status_id", models.CharField(blank=True, default="", max_length=50)),
                (
                    "time_submitted",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "time_generated",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("url", models.CharField(blank=True, default="", max_length=500)),
                ("csv_url", models.CharField(blank=True, default="", max_length=500)),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                (
                    "vehicle_vin",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "vehicle_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "vehicle_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rtl_ifta",
                "ordering": ["-from_date"],
            },
        ),
        migrations.CreateModel(
            name="RtlTruck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rtl_id", models.CharField(max_length=100, unique=True)),
                (
                    "company_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("make", models.CharField(blank=True, default="", max_length=100)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                ("year", models.CharField(blank=True, default="", max_length=10)),
                ("vin", models.CharField(blank=True, default="", max_length=50)),
                (
                    "plate_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "eld_serial_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "rtl_updated_at",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rtl_truck",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RtlDriverStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rtl_id", models.CharField(max_length=100, unique=True)),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_lon", models.FloatField(blank=True, null=True)),
                (
                    "location_state",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "location_timestamp",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "vehicle_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "vehicle_vin",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "hos_event_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "hos_event_time",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("daily_hours_driven", models.FloatField(blank=True, null=True)),
                ("daily_hours_on_duty", models.FloatField(blank=True, null=True)),
                ("eta", models.CharField(blank=True, default="", max_length=50)),
                (
                    "rtl_updated_at",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "rtl_driver",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latest_status",
                        to="integrations.rtldriver",
                        to_field="rtl_id",
                    ),
                ),
            ],
            options={
                "db_table": "rtl_driver_latest_status",
            },
        ),
        migrations.CreateModel(
            name="RtlTruckStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rtl_id", models.CharField(max_length=100, unique=True)),
                ("vin", models.CharField(blank=True, default="", max_length=50)),
                ("odometer", models.FloatField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("timestamp", models.CharField(blank=True, default="", max_length=50)),
                (
                    "calculated_location",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "rtl_updated_at",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "rtl_truck",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latest_status",
                        to="integrations.rtltruck",
                        to_field="rtl_id",
                    ),
                ),
            ],
            options={
                "db_table": "rtl_truck_latest_status",
            },
        ),
    ]
