# Generated by Django 5.2.15 on 2026-06-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rtldriverstatus",
            name="violations",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
