# Generated by Django 5.2.15 on 2026-06-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_add_violations_to_rtl_driver_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rtldriverstatus",
            name="location_calculated",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
