# Generated by Django 5.2.15 on 2026-06-23 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carriers", "__first__"),
        ("fleet", "__first__"),
        ("locations", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "driver_types",
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active"), (-1, "Terminated")],
                        default=1,
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.CharField(blank=True, default="", max_length=300)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                (
                    "social_security_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "license_file",
                    models.FileField(
                        blank=True, null=True, upload_to="drivers/licenses/"
                    ),
                ),
                ("license_expiration", models.DateField(blank=True, null=True)),
                (
                    "medical_card_file",
                    models.FileField(
                        blank=True, null=True, upload_to="drivers/medical_cards/"
                    ),
                ),
                ("medical_card_expiration", models.DateField(blank=True, null=True)),
                (
                    "residence_card_file",
                    models.FileField(
                        blank=True, null=True, upload_to="drivers/residence_cards/"
                    ),
                ),
                (
                    "application_file",
                    models.FileField(
                        blank=True, null=True, upload_to="drivers/applications/"
                    ),
                ),
                (
                    "lease_agreement_file",
                    models.FileField(
                        blank=True, null=True, upload_to="drivers/lease_agreements/"
                    ),
                ),
                (
                    "mvr_file",
                    models.FileField(blank=True, null=True, upload_to="drivers/mvr/"),
                ),
                ("mvr_expiration", models.DateField(blank=True, null=True)),
                (
                    "social_security_file",
                    models.FileField(
                        blank=True, null=True, upload_to="drivers/social_security/"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="drivers/photos/"
                    ),
                ),
                ("contract", models.BooleanField(default=False)),
                ("miles_empty", models.FloatField(default=0)),
                ("miles_full", models.FloatField(default=0)),
                ("percent", models.FloatField(default=0)),
                ("insurance", models.FloatField(default=0)),
                ("eld", models.FloatField(default=0)),
                ("worker_comp", models.FloatField(default=0)),
                ("factor", models.FloatField(default=0)),
                ("factor_fee", models.FloatField(default=0)),
                ("carrier_start_date", models.DateField(blank=True, null=True)),
                ("carrier_end_date", models.DateField(blank=True, null=True)),
                ("carrier_end_reason", models.TextField(blank=True, default="")),
                ("endorsements", models.IntegerField(default=0)),
                ("restrictions", models.IntegerField(default=0)),
                ("on_vacation", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drivers",
                        to="carriers.carrier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_drivers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fuel_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drivers",
                        to="fleet.card",
                    ),
                ),
                (
                    "license_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drivers",
                        to="locations.state",
                    ),
                ),
                (
                    "team_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_partners",
                        to="drivers.driver",
                    ),
                ),
                (
                    "driver_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drivers",
                        to="drivers.drivertype",
                    ),
                ),
            ],
            options={
                "db_table": "drivers",
            },
        ),
        migrations.CreateModel(
            name="DriverDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.IntegerField(
                        choices=[
                            (1, "License"),
                            (2, "Medical Card"),
                            (3, "MVR / Record"),
                        ]
                    ),
                ),
                ("file", models.FileField(upload_to="drivers/documents/")),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "db_table": "driver_documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
