# Generated by Django 5.2.15 on 2026-06-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_drivervacation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverdocument",
            name="document_type",
            field=models.IntegerField(
                choices=[
                    (1, "License"),
                    (2, "Medical Card"),
                    (3, "MVR / Record"),
                    (4, "Residence Card"),
                    (5, "Application"),
                    (6, "Lease Agreement"),
                    (7, "Social Security Card"),
                ]
            ),
        ),
    ]
