# Generated by Codex on 2026-07-01

from decimal import Decimal

from django.db import migrations, models


def copy_contract_to_legacy(apps, schema_editor):
    Driver = apps.get_model("drivers", "Driver")
    for driver in Driver.objects.all().only("id", "contract", "contract_legacy"):
        driver.contract_legacy = 1 if driver.contract else 0
        driver.save(update_fields=["contract_legacy"])


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_alter_driverdocument_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="contract_legacy",
            field=models.IntegerField(
                choices=[
                    (0, "By percent"),
                    (1, "By miles"),
                    (2, "By percent no expenses"),
                ],
                default=0,
            ),
        ),
        migrations.RunPython(copy_contract_to_legacy, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="driver",
            name="contract",
        ),
        migrations.RenameField(
            model_name="driver",
            old_name="contract_legacy",
            new_name="contract",
        ),
        migrations.AddField(
            model_name="driver",
            name="weekly_rate",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=7,
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="pay_vacation",
            field=models.IntegerField(choices=[(0, "Yes"), (1, "Not")], default=0),
        ),
        migrations.AddField(
            model_name="driver",
            name="eld_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="driver",
            name="factoring_account_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
