# Generated by Codex on 2026-07-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0004_driver_legacy_parity_fields"),
        (
            "fleet",
            "0008_add_maintenance_miles_is_done_driven_miles_to_truck_maintenance",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drivers",
                to="fleet.truckowner",
            ),
        ),
    ]
