# Generated by Django 5.2.15 on 2026-06-23 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0001_initial"),
        ("fleet", "0001_initial"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CabinType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "cabin_types",
            },
        ),
        migrations.CreateModel(
            name="EngineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "engine_types",
            },
        ),
        migrations.CreateModel(
            name="LossPayee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "loss_payees",
            },
        ),
        migrations.CreateModel(
            name="Make",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "makes",
            },
        ),
        migrations.CreateModel(
            name="TireSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "tire_sizes",
            },
        ),
        migrations.CreateModel(
            name="TrailerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "trailer_types",
            },
        ),
        migrations.CreateModel(
            name="TransmissionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "transmission_types",
            },
        ),
        migrations.CreateModel(
            name="TruckOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
                (
                    "owner_type",
                    models.IntegerField(
                        choices=[(1, "Company"), (2, "Owner Operator")], default=2
                    ),
                ),
                ("worker_comp", models.FloatField(default=0)),
                ("factor_dispatch", models.FloatField(default=0)),
                ("factor_fee", models.FloatField(default=0)),
                ("percent", models.FloatField(default=0)),
                ("insurance", models.FloatField(default=0)),
                ("truck_amount", models.FloatField(default=0)),
                ("driver_amount", models.FloatField(default=0)),
                ("truck_yard_rent", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "truck_owners",
            },
        ),
        migrations.CreateModel(
            name="TruckType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "truck_types",
            },
        ),
        migrations.CreateModel(
            name="Trailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=60, unique=True)),
                ("vin", models.CharField(blank=True, default="", max_length=100)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("width", models.FloatField(default=0)),
                ("height", models.FloatField(default=0)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "annual_inspection_file",
                    models.FileField(
                        blank=True, null=True, upload_to="trailers/inspections/"
                    ),
                ),
                (
                    "annual_inspection_expiration",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "registration_file",
                    models.FileField(
                        blank=True, null=True, upload_to="trailers/registration/"
                    ),
                ),
                (
                    "agreement_file",
                    models.FileField(
                        blank=True, null=True, upload_to="trailers/agreements/"
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("purchase_cost", models.FloatField(default=0)),
                ("is_rented", models.BooleanField(default=False)),
                (
                    "loss_payee",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_trailers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plate_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trailers",
                        to="locations.state",
                    ),
                ),
                (
                    "trailer_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trailers",
                        to="fleet.trailertype",
                    ),
                ),
            ],
            options={
                "db_table": "trailers",
            },
        ),
        migrations.CreateModel(
            name="TrailerMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("miles", models.FloatField(default=0)),
                ("miles_alert", models.IntegerField(default=0)),
                ("time_alert", models.IntegerField(default=0)),
                ("time_year", models.IntegerField(default=0)),
                ("time_month", models.IntegerField(default=0)),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="fleet.trailer",
                    ),
                ),
            ],
            options={
                "db_table": "trailer_maintenance",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=60, unique=True)),
                ("vin", models.CharField(blank=True, default="", max_length=100)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
                ("plate", models.CharField(blank=True, default="", max_length=30)),
                (
                    "transponder",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("gross_weight", models.FloatField(default=0)),
                ("odometer_current", models.FloatField(default=0)),
                (
                    "avi_file",
                    models.FileField(blank=True, null=True, upload_to="trucks/avi/"),
                ),
                ("avi_expiration", models.DateField(blank=True, null=True)),
                (
                    "registration_file",
                    models.FileField(
                        blank=True, null=True, upload_to="trucks/registration/"
                    ),
                ),
                ("registration_expiration", models.DateField(blank=True, null=True)),
                (
                    "agreement_file",
                    models.FileField(
                        blank=True, null=True, upload_to="trucks/agreements/"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="trucks/photos/"
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("purchase_cost", models.FloatField(default=0)),
                ("is_leased", models.BooleanField(default=False)),
                (
                    "leased_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("loan_term", models.CharField(blank=True, default="", max_length=100)),
                (
                    "interest_rate",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "monthly_bill",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "remaining_balance",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("carrier_start_date", models.DateField(blank=True, null=True)),
                ("carrier_end_date", models.DateField(blank=True, null=True)),
                ("carrier_end_reason", models.TextField(blank=True, default="")),
                (
                    "mac_address",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "eld_company",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cabin_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trucks",
                        to="fleet.cabintype",
                    ),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trucks",
                        to="carriers.carrier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_trucks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispatcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatched_trucks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engine_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trucks",
                        to="fleet.enginetype",
                    ),
                ),
                (
                    "fuel_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trucks",
                        to="fleet.card",
                    ),
                ),
                (
                    "loss_payee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trucks",
                        to="fleet.losspayee",
                    ),
                ),
                (
                    "make",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trucks",
                        to="fleet.make",
                    ),
                ),
                (
                    "tire_size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trucks",
                        to="fleet.tiresize",
                    ),
                ),
                (
                    "transmission_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trucks",
                        to="fleet.transmissiontype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trucks",
                        to="fleet.truckowner",
                    ),
                ),
                (
                    "truck_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trucks",
                        to="fleet.trucktype",
                    ),
                ),
            ],
            options={
                "db_table": "trucks",
            },
        ),
        migrations.CreateModel(
            name="TruckMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("miles_alert", models.IntegerField(default=0)),
                ("time_alert", models.IntegerField(default=0)),
                ("time_year", models.IntegerField(default=0)),
                ("time_month", models.IntegerField(default=0)),
                ("odometer_start", models.FloatField(default=0)),
                ("odometer_current", models.FloatField(default=0)),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="fleet.truck",
                    ),
                ),
            ],
            options={
                "db_table": "truck_maintenance",
                "ordering": ["-date"],
            },
        ),
    ]
