# Generated by Django 5.2.15 on 2026-06-23 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
        ("fleet", "0002_cabintype_enginetype_losspayee_make_tiresize_and_more"),
        ("locations", "0002_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("address", models.CharField(max_length=300)),
                (
                    "police_report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="accidents/police_reports/"
                    ),
                ),
                (
                    "post_accident_file",
                    models.FileField(
                        blank=True, null=True, upload_to="accidents/post_accident/"
                    ),
                ),
                ("crash_number", models.CharField(max_length=100)),
                ("tow_aways", models.BooleanField(default=False)),
                ("death_count", models.PositiveIntegerField(default=0)),
                ("fatal_injuries", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accidents",
                        to="locations.city",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_accidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accidents",
                        to="drivers.driver",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accidents",
                        to="locations.state",
                    ),
                ),
                (
                    "trailer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accidents",
                        to="fleet.trailer",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accidents",
                        to="fleet.truck",
                    ),
                ),
            ],
            options={
                "db_table": "accidents",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AccidentPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="accidents/pictures/")),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("rank", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="fleet.accident",
                    ),
                ),
            ],
            options={
                "db_table": "accident_pictures",
                "ordering": ["rank", "created_at"],
            },
        ),
    ]
