# Generated by Django 5.2.15 on 2026-06-23 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_accident_accidentpicture"),
    ]

    operations = [
        migrations.CreateModel(
            name="TruckMilesReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miles_resets",
                        to="fleet.truck",
                    ),
                ),
            ],
            options={
                "db_table": "truck_miles_reset",
                "ordering": ["-date"],
            },
        ),
    ]
