# Generated by Django 5.2.15 on 2026-06-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0004_truckmilesreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailertype",
            name="short_name",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="trailertype",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
