# Generated by Django 5.2.15 on 2026-06-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0005_add_short_name_to_trailer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="truck",
            name="leased_file",
            field=models.FileField(blank=True, null=True, upload_to="trucks/leased/"),
        ),
    ]
