# Generated by Django 5.2.15 on 2026-06-24 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0002_factor"),
        ("fleet", "0006_truck_leased_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailer",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trailers",
                to="carriers.carrier",
            ),
        ),
        migrations.AddField(
            model_name="trailer",
            name="carrier_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trailer",
            name="carrier_end_reason",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="trailer",
            name="carrier_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trailer",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_trailers",
                to="fleet.truckowner",
            ),
        ),
    ]
