# Generated by Django 5.2.15 on 2026-06-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0007_trailer_carrier_owner_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="truckmaintenance",
            name="driven_miles",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="truckmaintenance",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="truckmaintenance",
            name="maintenance_miles",
            field=models.FloatField(default=0),
        ),
    ]
