# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fleet",
            "0008_add_maintenance_miles_is_done_driven_miles_to_truck_maintenance",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="truckmilesreset",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterModelOptions(
            name="truckmilesreset",
            options={"ordering": ["-date", "-id"]},
        ),
    ]
