# Generated by Django 5.2.15 on 2026-07-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0009_truck_miles_reset_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="truck",
            name="eld_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="truck",
            name="factoring_account_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="truck",
            name="odometer_start",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="TruckStoredFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(choices=[(1, "AVI"), (2, "Registration")]),
                ),
                ("file", models.FileField(upload_to="trucks/stored/")),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_files",
                        to="fleet.truck",
                    ),
                ),
            ],
            options={
                "db_table": "truck_stored_files",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
