# Generated by Django 5.2.15 on 2026-07-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0010_truck_report_and_stored_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrailerStoredFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="trailers/stored/")),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_files",
                        to="fleet.trailer",
                    ),
                ),
            ],
            options={
                "db_table": "trailer_stored_files",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
