# Generated by Django 5.2.15 on 2026-06-23 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brokers", "0002_business"),
        ("carriers", "0001_initial"),
        ("drivers", "0001_initial"),
        ("fleet", "0002_cabintype_enginetype_losspayee_make_tiresize_and_more"),
        ("locations", "0002_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Load",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=60, unique=True)),
                ("miles", models.FloatField(default=0.0)),
                ("miles_empty", models.FloatField(default=0.0)),
                ("weight", models.FloatField(default=0.0)),
                ("pickup_date", models.DateField()),
                ("pickup_address", models.CharField(max_length=500)),
                ("dropoff_date", models.DateField()),
                ("dropoff_address", models.CharField(max_length=500)),
                ("payment", models.FloatField(default=0.0)),
                ("detention", models.FloatField(default=0.0)),
                ("lumper", models.FloatField(default=0.0)),
                (
                    "lumper_paid_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("company", "Company"),
                            ("broker", "Broker"),
                            ("driver", "Driver"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("drop_trailer", models.FloatField(default=0.0)),
                (
                    "broker_contacts",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("shipper_rating", models.IntegerField(default=0)),
                ("receiver_rating", models.IntegerField(default=0)),
                (
                    "rate_file",
                    models.FileField(blank=True, null=True, upload_to="loads/rates/"),
                ),
                (
                    "bill_file",
                    models.FileField(blank=True, null=True, upload_to="loads/bills/"),
                ),
                (
                    "lumper_file",
                    models.FileField(blank=True, null=True, upload_to="loads/lumpers/"),
                ),
                (
                    "detention_file",
                    models.FileField(
                        blank=True, null=True, upload_to="loads/detentions/"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Registered"),
                            (2, "Started"),
                            (3, "Finished"),
                            (4, "Detention Pending"),
                            (5, "Cancelled"),
                        ],
                        default=1,
                    ),
                ),
                ("execute", models.BooleanField(default=False)),
                ("invoiced", models.BooleanField(default=False)),
                ("paid", models.BooleanField(default=False)),
                ("owner_invoiced", models.BooleanField(default=False)),
                ("owner_invoice_number", models.IntegerField(default=0)),
                ("owner_paid", models.BooleanField(default=False)),
                ("history", models.BooleanField(default=False)),
                ("move", models.BooleanField(default=False)),
                ("drivers_paid", models.BooleanField(default=False)),
                ("is_drop", models.BooleanField(default=False)),
                ("days_in_drop", models.IntegerField(default=0)),
                ("rc_notified", models.BooleanField(default=False)),
                ("bol_notified", models.BooleanField(default=False)),
                ("lumper_notified", models.BooleanField(default=False)),
                ("detention_notified", models.BooleanField(default=False)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("eta", models.IntegerField(blank=True, null=True)),
                ("accounting_day", models.IntegerField(blank=True, null=True)),
                ("details", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loads",
                        to="brokers.broker",
                    ),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loads",
                        to="carriers.carrier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_loads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispatcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatched_loads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loads",
                        to="drivers.driver",
                    ),
                ),
                (
                    "drop_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drop_loads",
                        to="fleet.trailer",
                    ),
                ),
                (
                    "dropoff_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dropoff_loads",
                        to="locations.city",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_loads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pickup_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_loads",
                        to="locations.city",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receiver_loads",
                        to="brokers.business",
                    ),
                ),
                (
                    "shipper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipper_loads",
                        to="brokers.business",
                    ),
                ),
                (
                    "team_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_loads",
                        to="drivers.driver",
                    ),
                ),
                (
                    "trailer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loads",
                        to="fleet.trailer",
                    ),
                ),
                (
                    "trailer_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loads",
                        to="fleet.trailertype",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loads",
                        to="fleet.truck",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_loads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "loads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoadStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stop_type",
                    models.IntegerField(
                        choices=[(1, "Pickup"), (2, "Dropoff")], default=1
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                (
                    "bol_file",
                    models.FileField(
                        blank=True, null=True, upload_to="loads/stops/bol/"
                    ),
                ),
                ("business_rating", models.IntegerField(blank=True, null=True)),
                ("is_drop", models.BooleanField(default=False)),
                ("address", models.CharField(max_length=500)),
                ("details", models.TextField(blank=True, default="")),
                ("is_fcfs", models.BooleanField(default=False)),
                ("po_number", models.CharField(blank=True, default="", max_length=100)),
                ("commodity", models.CharField(blank=True, default="", max_length=100)),
                (
                    "temperature",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "driver_notes",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("departed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stops",
                        to="brokers.business",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stops",
                        to="locations.city",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stop_drivers",
                        to="drivers.driver",
                    ),
                ),
                (
                    "load",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="loads.load",
                    ),
                ),
                (
                    "trailer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stop_trailers",
                        to="fleet.trailer",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stop_trucks",
                        to="fleet.truck",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_stops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "load_stops",
                "ordering": ["from_date", "stop_type"],
            },
        ),
    ]
