# Generated by Django 5.2.15 on 2026-06-23 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0001_initial"),
        ("loads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="dispatch_invoice_percent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loads",
                to="dispatch.dispatcherworkinvoicebypercent",
            ),
        ),
    ]
