# Generated by Django 5.2.15 on 2026-06-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loads", "0002_load_dispatch_invoice_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="dropoff_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="load",
            name="pickup_date",
            field=models.DateTimeField(),
        ),
    ]
