# Generated by Django 5.2.15 on 2026-06-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loads", "0004_alter_load_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="load",
            name="drop_place",
            field=models.IntegerField(
                blank=True, choices=[(0, "In drop off"), (1, "In pick up")], null=True
            ),
        ),
    ]
