# Generated by Django 5.2.15 on 2026-06-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loads", "0005_alter_load_drop_place_to_integer"),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="executed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
