# Generated by Django 5.2.15 on 2026-06-23 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        ("fleet", "0002_cabintype_enginetype_losspayee_make_tiresize_and_more"),
        ("loads", "0001_initial"),
        ("locations", "0002_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_main", models.BooleanField(default=False)),
                ("is_assistant", models.BooleanField(default=False)),
                ("no_tax", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "accounts",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CategoryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "unit_of_measure",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "category_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_truck_part", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                (
                    "cabin_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="fleet.cabintype",
                    ),
                ),
                (
                    "engine_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="fleet.enginetype",
                    ),
                ),
                (
                    "transmission_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="fleet.transmissiontype",
                    ),
                ),
                (
                    "category_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="accounting.categorytype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DriverInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("invoice_type", models.IntegerField(default=0)),
                ("contract", models.IntegerField(default=0)),
                ("miles_empty", models.FloatField(default=0.0)),
                ("miles_full", models.FloatField(default=0.0)),
                ("percent", models.FloatField(default=0.0)),
                (
                    "vacation_now",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("vacation_pay", models.BooleanField(default=False)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Closed"), (1, "Open")], default=1
                    ),
                ),
                ("load_list", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_driver_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="drivers.driver",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_driver_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "driver_invoices",
                "ordering": ["-date", "-number"],
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("quantity", models.FloatField(default=1.0)),
                ("amount", models.FloatField(default=0.0)),
                ("detail", models.TextField(blank=True, default="")),
                (
                    "record_type",
                    models.IntegerField(
                        choices=[(1, "Income"), (2, "Expense"), (3, "Transfer")],
                        default=2,
                    ),
                ),
                ("category_expire", models.BooleanField(default=False)),
                ("category_expire_date", models.DateField(blank=True, null=True)),
                ("is_automatic", models.BooleanField(default=False)),
                ("progress", models.IntegerField(default=0)),
                ("follow", models.IntegerField(default=0)),
                ("position", models.IntegerField(default=0)),
                ("product", models.CharField(blank=True, default="", max_length=255)),
                (
                    "transaction_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="accounting.account",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="fleet.card",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="accounting.category",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="locations.city",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispatcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatched_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="drivers.driver",
                    ),
                ),
                (
                    "load",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="loads.load",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="fleet.truckowner",
                    ),
                ),
                (
                    "team_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_records",
                        to="drivers.driver",
                    ),
                ),
                (
                    "trailer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="fleet.trailer",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="fleet.truck",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "records",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OwnerInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("date", models.DateField()),
                (
                    "owner_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("company", "Company"),
                            ("owner_operator", "Owner Operator"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("contract", models.IntegerField(default=0)),
                ("percent", models.FloatField(default=0.0)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Closed"), (1, "Open")], default=1
                    ),
                ),
                ("worker_comp", models.FloatField(default=0.0)),
                ("factor_dispatch", models.FloatField(default=0.0)),
                ("factor_fee", models.FloatField(default=0.0)),
                ("check_amount", models.FloatField(default=0.0)),
                ("income_by_rate", models.FloatField(default=0.0)),
                ("income_by_detention", models.FloatField(default=0.0)),
                ("income_by_lumper", models.FloatField(default=0.0)),
                ("income_by_driver", models.FloatField(default=0.0)),
                ("fuel_expenses", models.FloatField(default=0.0)),
                ("scale_expenses", models.FloatField(default=0.0)),
                ("insurance_expenses", models.FloatField(default=0.0)),
                ("yard_expenses", models.FloatField(default=0.0)),
                ("factor_expenses", models.FloatField(default=0.0)),
                ("toll_expenses", models.FloatField(default=0.0)),
                ("eld_expenses", models.FloatField(default=0.0)),
                ("load_list", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_owner_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="fleet.truckowner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_owner_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner_invoices",
                        to="accounting.record",
                    ),
                ),
            ],
            options={
                "db_table": "owner_invoices",
                "ordering": ["-date", "-number"],
            },
        ),
    ]
