# Generated by Django 5.2.15 on 2026-06-23 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        ("fleet", "0004_truckmilesreset"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardGain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("gain", models.FloatField()),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gains",
                        to="fleet.card",
                    ),
                ),
            ],
            options={
                "db_table": "cardsgain",
                "ordering": ["-date"],
            },
        ),
    ]
