# Generated by Django 5.2.15 on 2026-06-24 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_cardgain"),
        ("carriers", "0002_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="carriers.carrier",
            ),
        ),
    ]
