# Generated by Django 5.2.15 on 2026-06-23 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (10, "Active")], default=10
                    ),
                ),
                ("is_dispatcher", models.BooleanField(default=False)),
                (
                    "dispatcher_type",
                    models.IntegerField(
                        choices=[(0, "None"), (1, "By Percent"), (2, "By Hour")],
                        default=0,
                    ),
                ),
                ("is_main_dispatcher", models.BooleanField(default=False)),
                ("percent", models.FloatField(default=0)),
                ("hours", models.FloatField(default=0)),
                ("start_hour", models.TimeField(blank=True, null=True)),
                ("end_hour", models.TimeField(blank=True, null=True)),
                ("color", models.CharField(blank=True, default="", max_length=20)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="users/photos/"),
                ),
                ("carriers_access", models.JSONField(blank=True, default=list)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
