# Generated by Django 5.2.15 on 2026-06-24 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplayOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("truck", models.CharField(default="", max_length=800)),
                ("trailer", models.CharField(default="", max_length=800)),
                ("driver", models.CharField(default="", max_length=800)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "display options",
                "db_table": "display_options",
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_hours_work_dispatcher", models.TimeField(default="08:00")),
                ("end_hours_work_dispatcher", models.TimeField(default="17:00")),
                ("dispatcher_invoice_hour", models.IntegerField(default=1000)),
                ("dispatcher_invoice_percent", models.IntegerField(default=1000)),
                ("driver_invoice", models.IntegerField(default=1000)),
                ("owner_invoice", models.IntegerField(default=1000)),
                ("carrier", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_config",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="user",
            name="carrier",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="contract",
            field=models.IntegerField(
                choices=[(0, "By Percent"), (1, "By Hour")], default=0
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dispatcher_access",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="main_dispatcher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assistant_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.position",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_security_number",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="dispatcher_type",
            field=models.IntegerField(
                choices=[(0, "Main"), (1, "Assistant")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
