# Generated by Django 5.2.15 on 2026-06-23 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("zip", models.CharField(blank=True, default="", max_length=10)),
                ("active", models.BooleanField(default=True)),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cities",
                        to="locations.state",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "cities",
                "db_table": "cities",
                "ordering": ["name"],
            },
        ),
    ]
