# Generated by Django 5.2.15 on 2026-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="timezone",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
