# Generated by Django 5.2.15 on 2026-06-23 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        ("fleet", "0004_truckmilesreset"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRecordFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Pilot"), (2, "Statement")], default=1
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("sha1_file", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "imported_file",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriverFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(choices=[(1, "License"), (2, "Medical Card")]),
                ),
                ("file", models.FileField(upload_to="documents/drivers/")),
                ("expiry_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "db_table": "driver_file",
                "ordering": ["-expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="TrailerFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(choices=[(1, "AVI"), (2, "Registration")]),
                ),
                ("file", models.FileField(upload_to="documents/trailers/")),
                ("expiry_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="fleet.trailer",
                    ),
                ),
            ],
            options={
                "db_table": "trailer_file",
                "ordering": ["-expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="TruckFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(choices=[(1, "AVI"), (2, "Registration")]),
                ),
                ("file", models.FileField(upload_to="documents/trucks/")),
                ("expiry_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="fleet.truck",
                    ),
                ),
            ],
            options={
                "db_table": "truck_file",
                "ordering": ["-expiry_date"],
            },
        ),
    ]
