# Generated by Django 5.2.15 on 2026-06-23 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carriers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mc", models.CharField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("dba_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=255)),
                (
                    "accounting_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=0
                    ),
                ),
                (
                    "setup_packet_file",
                    models.FileField(
                        blank=True, null=True, upload_to="brokers/packets/"
                    ),
                ),
                (
                    "factor_company",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "factor_account_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "buy_status",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "debtor_buy_status",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("details", models.TextField(blank=True, default="")),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brokers",
                        to="carriers.carrier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_brokers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_brokers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "brokers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BrokerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("phone", models.CharField(blank=True, default="", max_length=255)),
                ("team", models.BooleanField(default=False)),
                ("details", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="brokers.broker",
                    ),
                ),
            ],
            options={
                "db_table": "broker_contacts",
                "ordering": ["email"],
            },
        ),
    ]
