# Generated by Django 5.2.15 on 2026-06-24 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0002_business"),
        ("locations", "0002_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="broker",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brokers",
                to="locations.city",
            ),
        ),
        migrations.AddField(
            model_name="broker",
            name="mailing_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="broker",
            name="physical_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="broker",
            name="safer_operating_status",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="broker",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brokers",
                to="locations.state",
            ),
        ),
        migrations.AddField(
            model_name="broker",
            name="usdot_number",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="broker",
            name="zip",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddField(
            model_name="brokercontact",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="brokercontact",
            name="is_scam",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="broker",
            name="checked_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
