# Generated by Django 5.2.15 on 2026-06-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, max_digits=10, unique=True),
                ),
                ("percent", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "db_table": "factor",
                "ordering": ["value"],
            },
        ),
    ]
