# Generated by Django 5.2.15 on 2026-06-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0002_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="no_reply_password",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
