# Generated by Django 5.2.15 on 2026-06-23 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatcherWorkInvoiceByHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("date", models.DateField()),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("pay_per_hour", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Closed"), (1, "Open")], default=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_hour_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispatcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hour_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_hour_invoices",
                        to="accounting.record",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_hour_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dispatcher_work_invoice_by_hour",
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="DispatcherWorkInvoiceByPercent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("date", models.DateField()),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("percent", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Closed"), (1, "Open")], default=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_percent_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispatcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="percent_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_percent_invoices",
                        to="accounting.record",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_percent_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dispatcher_work_invoice_by_percent",
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="DispatcherWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("title", models.CharField(max_length=100)),
                ("session", models.CharField(blank=True, default="", max_length=100)),
                ("is_finished", models.BooleanField(default=False)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "dispatcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice_hour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_sessions",
                        to="dispatch.dispatcherworkinvoicebyhour",
                    ),
                ),
                (
                    "invoice_percent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_sessions",
                        to="dispatch.dispatcherworkinvoicebypercent",
                    ),
                ),
            ],
            options={
                "db_table": "dispatcher_work",
                "ordering": ["-start"],
            },
        ),
    ]
